language: bash
services: docker

env:
  - VERSION=7.2
  - VERSION=7.1
  - VERSION=7.0
  - VERSION=5.6

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="vdubyna/magento-container:${VERSION}-php"

script:
  - travis_retry docker build -t "$image" .

after_script:
  - docker images

after_success:
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
  - docker push vdubyna/magento-container:${VERSION}-php;
